In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("finaldata.json")

In [3]:
df

,CompanyName,Location,center,Lantitude,longitude,state,CountryofLaunch,Rocket,flightnumber,StatusRocket,StatusMission,CompanysCountryofOrigin,PrivateorState,DateTime,Year,Month,Day,Date,Time
0,SpaceX,LC-39A,Kennedy Space Center,28.524167,-80.650833,Florida,USA,50,Starlink V1 L9 & BlackSky,StatusActive,Success,USA,P,2020-08-07 05:12:00+00:00,2020,8,7,2020-07-08,5:12
1,CASIC,Site 9401 (SLS-2),Jiuquan Satellite Launch Center,40.960556,100.298333,,China,29.75,Gaofen-9 04 & Q-SAT,StatusActive,Success,China,S,2020-08-06 04:01:00+00:00,2020,8,6,2020-06-08,4:01
2,SpaceX,Pad A,Boca Chica,25.997000,-97.157,Texas,USA,,150 Meter Hop,StatusActive,Success,USA,P,2020-08-04 23:57:00+00:00,2020,8,4,2020-04-08,23:57
3,Roscosmos,Site 200/39,Baikonur Cosmodrome,45.965000,63.305,,Kazakhstan,65,Ekspress-80 & Ekspress-103,StatusActive,Success,Russia,S,2020-07-30 21:25:00+00:00,2020,7,30,2020-07-30,21:25
4,ULA,SLC-41,Cape Canaveral AFS,28.583333,-80.583056,Florida,USA,145,Perseverance,StatusActive,Success,USA,P,2020-07-30 11:50:00+00:00,2020,7,30,2020-07-30,11:50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4319,US Navy,LC-18A,Cape Canaveral AFS,28.583333,-80.583056,Florida,USA,,Vanguard TV3BU,StatusRetired,Failure,USA,S,1958-02-05 07:33:00+00:00,1958,2,5,1958-05-02,7:33
4320,AMBA,LC-26A,Cape Canaveral AFS,28.583333,-80.583056,Florida,USA,,Explorer 1,StatusRetired,Success,USA,S,1958-02-01 03:48:00+00:00,1958,2,1,1958-01-02,3:48
4321,US Navy,LC-18A,Cape Canaveral AFS,28.583333,-80.583056,Florida,USA,,Vanguard TV3,StatusRetired,Failure,USA,S,1957-12-06 16:44:00+00:00,1957,12,6,1957-06-12,16:44
4322,RVSN USSR,Site 1/5,Baikonur Cosmodrome,45.965000,63.305,,Kazakhstan,,Sputnik-2,StatusRetired,Success,Russia,S,1957-11-03 02:30:00+00:00,1957,11,3,1957-03-11,2:30
4323,RVSN USSR,Site 1/5,Baikonur Cosmodrome,45.965000,63.305,,Kazakhstan,,Sputnik-1,StatusRetired,Success,Russia,S,1957-10-04 19:28:00+00:00,1957,10,4,1957-04-10,19:28

In [ ]:
column_names = ['name', 'value', 'year', 'lastValue', 'rank']